/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Guest_2
 */
public class frmMenuUtama extends javax.swing.JFrame {

    /**
     * Creates new form frmMenuUtama
     */
    public frmMenuUtama() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        frmSubKatagori = new javax.swing.JMenuItem();
        frmSubStok = new javax.swing.JMenuItem();
        frmSubPengguna = new javax.swing.JMenuItem();
        frmSubCetak = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jMenuBar1.setBackground(new java.awt.Color(51, 153, 255));

        jMenu1.setBackground(new java.awt.Color(51, 153, 255));
        jMenu1.setForeground(new java.awt.Color(0, 0, 0));
        jMenu1.setText("File");

        frmSubKatagori.setBackground(new java.awt.Color(255, 255, 255));
        frmSubKatagori.setForeground(new java.awt.Color(0, 0, 0));
        frmSubKatagori.setText("-Input Katagori");
        frmSubKatagori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frmSubKatagoriActionPerformed(evt);
            }
        });
        jMenu1.add(frmSubKatagori);

        frmSubStok.setBackground(new java.awt.Color(255, 255, 255));
        frmSubStok.setForeground(new java.awt.Color(0, 0, 0));
        frmSubStok.setText("-Stok");
        frmSubStok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frmSubStokActionPerformed(evt);
            }
        });
        jMenu1.add(frmSubStok);

        frmSubPengguna.setBackground(new java.awt.Color(255, 255, 255));
        frmSubPengguna.setForeground(new java.awt.Color(0, 0, 0));
        frmSubPengguna.setText("-Pengguna");
        frmSubPengguna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frmSubPenggunaActionPerformed(evt);
            }
        });
        jMenu1.add(frmSubPengguna);

        jMenuBar1.add(jMenu1);

        frmSubCetak.setBackground(new java.awt.Color(0, 153, 255));
        frmSubCetak.setForeground(new java.awt.Color(0, 0, 0));
        frmSubCetak.setText("Report");

        jMenuItem5.setBackground(new java.awt.Color(255, 255, 255));
        jMenuItem5.setForeground(new java.awt.Color(0, 0, 0));
        jMenuItem5.setText("-Cetak Stok");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        frmSubCetak.add(jMenuItem5);

        jMenuBar1.add(frmSubCetak);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void frmSubKatagoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frmSubKatagoriActionPerformed
        // TODO add your handling code here:
        frmKatagori objKatagori = new frmKatagori(); 
	objKatagori.show();
    }//GEN-LAST:event_frmSubKatagoriActionPerformed

    private void frmSubPenggunaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frmSubPenggunaActionPerformed
        // TODO add your handling code here:
        frmPengguna objPengguna = new frmPengguna(); 
	objPengguna.show();
    }//GEN-LAST:event_frmSubPenggunaActionPerformed

    private void frmSubStokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frmSubStokActionPerformed
        // TODO add your handling code here:
        frmStok objStok = new frmStok(); 
	objStok.show();
    }//GEN-LAST:event_frmSubStokActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        frmCetak objCetak = new frmCetak(); 
	objCetak.show();
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMenuUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu frmSubCetak;
    private javax.swing.JMenuItem frmSubKatagori;
    private javax.swing.JMenuItem frmSubPengguna;
    private javax.swing.JMenuItem frmSubStok;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem5;
    // End of variables declaration//GEN-END:variables
}
