//import  komponen
import  java.awt.Dimension;
import  java.awt.Toolkit;
import  java.awt.event.KeyEvent;
import  java.sql.ResultSet;
import  java.sql.Statement;
import  javax.swing.JOptionPane;
import  javax.swing.table.DefaultTableModel;
import  javax.swing.table.TableColumn;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Guest_2
 */
public class frmPengguna extends javax.swing.JFrame {

    //membuat  objek  dari  kelas  clsPengguna
    clsPengguna  objPengguna  =  new  clsPengguna();
    
    //mendeklarasikan  variabel
    private  TableColumn  column;
    /**
     * Creates new form frmPengguna
     */
    public frmPengguna() {
        initComponents();
        
        //Untuk  mematikan  tombol  close
	setDefaultCloseOperation(frmKatagori.DO_NOTHING_ON_CLOSE);
		
        //koneksi  ke  database
	objPengguna.AksesData();  //terhubung  ke  database
	IsiTabel();  //mengisi  jTable  dgn  data
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        txtNama = new javax.swing.JTextField();
        txtPassword = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTabel = new javax.swing.JTable();
        btnBaru = new javax.swing.JButton();
        btnSimpan = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnKeluar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jLabel1.setText("ID Pengguna :");

        jLabel2.setText("Nama Pengguna :");

        jLabel3.setText("Password :");

        txtID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtIDKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIDKeyTyped(evt);
            }
        });

        txtNama.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNamaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNamaKeyTyped(evt);
            }
        });

        txtPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPasswordKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPasswordKeyTyped(evt);
            }
        });

        jTabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Nama", "Password"
            }
        ));
        jTabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabelMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTabel);

        btnBaru.setText("Baru");
        btnBaru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBaruActionPerformed(evt);
            }
        });

        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });
        btnSimpan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnSimpanKeyPressed(evt);
            }
        });

        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnKeluar.setText("Keluar");
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtNama, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                                    .addComponent(txtPassword)
                                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btnBaru)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSimpan)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnEdit)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnHapus)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnKeluar)))
                        .addGap(0, 71, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBaru)
                    .addComponent(btnSimpan)
                    .addComponent(btnEdit)
                    .addComponent(btnHapus)
                    .addComponent(btnKeluar))
                .addContainerGap(102, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBaruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBaruActionPerformed
        // TODO add your handling code here:
        try
	{
            BersihIsian();
            IsiTabel();
            txtID.requestFocus();
	}
	catch  (Exception  e)
	{
	}
    }//GEN-LAST:event_btnBaruActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        SimpanData();
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        if(txtID.getText().equals("")||txtNama.getText().equals(""))
	{
            JOptionPane.showMessageDialog(null,"Masukkan ID Pengguna");
	}
	else
	{
            try
            {
		objPengguna.AksesData();
		objPengguna.IdPengguna  =  txtID.getText();
		objPengguna.Nama  =  txtNama.getText();
		objPengguna.KataKunci  =  txtPassword.getText(); 

		objPengguna.Edit();
		objPengguna.res.executeUpdate(objPengguna.sql);
		objPengguna.conn.close();
		BersihIsian();
		IsiTabel();
		JOptionPane.showMessageDialog(null,"Data berhasil diupdate");
            }
            catch (Exception e)
            {
		JOptionPane.showMessageDialog(null,"Proses penyimpanan gagal/koneksi gagal");
		System.out.println(e.getMessage());
            }
	}
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        try
	{
            objPengguna.AksesData();
            objPengguna.IdPengguna  =  txtID.getText();
            objPengguna.Hapus();
            objPengguna.res.executeUpdate(objPengguna.sql);
            objPengguna.conn.close();
            IsiTabel();
            BersihIsian();
            JOptionPane.showMessageDialog(null,"Data berhasil dihapus");
	}
	catch  (Exception  e)
	{
            JOptionPane.showMessageDialog(null,"Proses penghapusan gagal/koneksi gagal");
            System.out.println(e.getMessage());
	}
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        // TODO add your handling code here:
        try
	{
            objPengguna.Keluar();
            dispose();
	}
	catch  (Exception  e)
	{
            JOptionPane.showMessageDialog(null,"Terjadi kesalahan");
            System.out.println(e.getMessage());
	}
    }//GEN-LAST:event_btnKeluarActionPerformed

    private void jTabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabelMouseClicked
        // TODO add your handling code here:
        int  baris  =  jTabel.getSelectedRow();
        
	String  kolom1  =  jTabel.getValueAt(baris,  0).toString();
	String  kolom2  =  jTabel.getValueAt(baris,  1).toString();
	String  kolom3  =  jTabel.getValueAt(baris,  2).toString(); 

	txtID.setText(kolom1);
	txtNama.setText(kolom2);
	txtPassword.setText(kolom3);
    }//GEN-LAST:event_jTabelMouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        //membuat  form  ditengah-tengah  sceeen
	Dimension  posisi  =  Toolkit.getDefaultToolkit().getScreenSize();
	int  x  =  (posisi.width  -  this.getWidth())/2;
	int  y  =  (posisi.height  -  this.getHeight())/2;
	this.setLocation(x,y);
    }//GEN-LAST:event_formWindowActivated

    private void txtIDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIDKeyPressed
        // TODO add your handling code here:
        if  (evt.getKeyCode()==  KeyEvent.VK_ENTER)
	{
            if  ((txtID.getText().length()  <  3)  ||  (txtID.getText().isEmpty()))
            {
		JOptionPane.showMessageDialog(this,"Panjang ID harus 3 digit","Informasi",
                JOptionPane.INFORMATION_MESSAGE);
		txtID.requestFocus();
            }
            else
            {
		txtNama.requestFocus();
            }
	}
    }//GEN-LAST:event_txtIDKeyPressed

    private void txtNamaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNamaKeyPressed
        // TODO add your handling code here:
        if  (evt.getKeyCode()==  KeyEvent.VK_ENTER)
	{
            if  (txtNama.getText().isEmpty())
            {
		JOptionPane.showMessageDialog(this,"Nama masih kosong","Informasi",
		JOptionPane.INFORMATION_MESSAGE);
		txtNama.requestFocus();
            }
            else
            {
		txtPassword.requestFocus();
            }
	}
    }//GEN-LAST:event_txtNamaKeyPressed

    private void txtPasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPasswordKeyPressed
        // TODO add your handling code here:
        if  (evt.getKeyCode()==  KeyEvent.VK_ENTER)
	{
            if  (txtPassword.getText().isEmpty())
            {
		JOptionPane.showMessageDialog(this, "Password masih kosong","Informasi",
		JOptionPane.INFORMATION_MESSAGE);
		txtPassword.requestFocus();
            }
            else
            {
		btnSimpan.requestFocus();
            }
	}
    }//GEN-LAST:event_txtPasswordKeyPressed

    private void txtIDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIDKeyTyped
        // TODO add your handling code here:
        //untuk  membatasi  3  karakter
	if  (txtID.getText().length()  >  2)
	evt.consume();
    }//GEN-LAST:event_txtIDKeyTyped

    private void txtNamaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNamaKeyTyped
        // TODO add your handling code here:
        //untuk  membatasi  3  karakter
	if  (txtNama.getText().length()  >  29)
	evt.consume();
    }//GEN-LAST:event_txtNamaKeyTyped

    private void txtPasswordKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPasswordKeyTyped
        // TODO add your handling code here:
        //untuk  membatasi  3  karakter
	if  (txtPassword.getText().length()  >  29)
	evt.consume();
    }//GEN-LAST:event_txtPasswordKeyTyped

    private void btnSimpanKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnSimpanKeyPressed
        // TODO add your handling code here:
        SimpanData();
    }//GEN-LAST:event_btnSimpanKeyPressed

    //Prosedur  membersihkan  isian  data
    public  void  BersihIsian()
    {
	txtID.setText("");
	txtID.requestFocus();
	txtNama.setText("");
	txtPassword.setText("");
    }

    //Prosedur  simpan  data
    private  void  SimpanData()
    {
	if(txtID.getText().equals("")||txtNama.getText().equals(""))
	{
            JOptionPane.showMessageDialog(null,"Data harus diisi semua");
	}
	else
	{
            try
            {
		objPengguna.AksesData();
		objPengguna.IdPengguna  =  txtID.getText();
		objPengguna.Nama  =  txtNama.getText();
		objPengguna.KataKunci  =  txtPassword.getText();
		objPengguna.Simpan();
		objPengguna.res.executeUpdate(objPengguna.sql);
		objPengguna.conn.close();
		BersihIsian();
		IsiTabel();
		JOptionPane.showMessageDialog(null,"Data berhasil disimpan");
            }
            catch (Exception e)
            {
		JOptionPane.showMessageDialog(null,"Proses penyimpanan gagal/koneksi gagal");
		System.out.println(e.getMessage());
            }
	}
    }
 
    //Prosedur  mengatur  kolom  jTable
    private  void  AturKolom()  
    {
	jTabel.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
	column  =  jTabel.getColumnModel().getColumn(0);
	column.setPreferredWidth(80);
	column  =  jTabel.getColumnModel().getColumn(1);
	column.setPreferredWidth(160);
	column  =  jTabel.getColumnModel().getColumn(2);
	column.setPreferredWidth(160);
    }

    //Prosedur  menampilkan  data  ke  jTable
    private  void  IsiTabel()  
    {
	DefaultTableModel  tabelmapel  =  new  DefaultTableModel(); 

	tabelmapel.addColumn("ID");
	tabelmapel.addColumn("Nama");
	tabelmapel.addColumn("Password");
	try
	{
            objPengguna.AksesData();
            objPengguna.TampilData(); 

            Statement  stat1  =  objPengguna.conn.createStatement();
            ResultSet  res1=stat1.executeQuery(objPengguna.sql);
            while  (res1.next())
            {
		tabelmapel.addRow(new Object[]{res1.getString(1),res1.getString(2),res1.getString(3)});
            }
            jTabel.setModel(tabelmapel);
            AturKolom();  //atur  kolom  jTable
	}
        catch  (Exception  e)
	{
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPengguna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPengguna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPengguna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPengguna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPengguna().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBaru;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTabel;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtPassword;
    // End of variables declaration//GEN-END:variables
}
