//import  komponen
import  java.awt.Dimension;
import  java.awt.Toolkit;
import  java.awt.event.KeyEvent;
import  java.sql.ResultSet;
import  java.sql.Statement;
import  javax.swing.JOptionPane;
import  javax.swing.table.DefaultTableModel;
import  javax.swing.table.TableColumn;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Guest_2
 */
public class frmStok extends javax.swing.JFrame {
    //membuat  objek  dari  kelas  clsKaryawan
    clsStok  objStok  =  new  clsStok();
    //Mendeklarasikan  variabel
    private  TableColumn  column;
    /**
     * Creates new form frmStok
     */
    public frmStok() {
        initComponents();
        //Untuk  mematikan  tombol  close
	setDefaultCloseOperation(frmKatagori.DO_NOTHING_ON_CLOSE);
	//koneksi  ke  database
	objStok.AksesData();
	IsiTabel();  //mengisi  jTable  dgn  data
	IsiComboKatagori();  //memanggil  prosedur
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtKode = new javax.swing.JTextField();
        txtNama = new javax.swing.JTextField();
        cboKatagori = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtHargaB = new javax.swing.JTextField();
        txtHargaJ = new javax.swing.JTextField();
        txtStok = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTabel = new javax.swing.JTable();
        btnBaru = new javax.swing.JButton();
        btnSimpan = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnKeluar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jLabel1.setText("Kode Barang :");

        jLabel2.setText("Nama Barang :");

        jLabel3.setText("Katagori        :");

        txtKode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtKodeKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtKodeKeyTyped(evt);
            }
        });

        txtNama.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNamaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNamaKeyTyped(evt);
            }
        });

        cboKatagori.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboKatagori.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cboKatagoriMouseClicked(evt);
            }
        });
        cboKatagori.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cboKatagoriKeyPressed(evt);
            }
        });

        jLabel4.setText("Harga Beli :");

        jLabel5.setText("Harga Jual :");

        jLabel6.setText("Stok         :");

        txtHargaB.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtHargaBKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtHargaBKeyTyped(evt);
            }
        });

        txtHargaJ.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtHargaJKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtHargaJKeyTyped(evt);
            }
        });

        txtStok.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtStokKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtStokKeyTyped(evt);
            }
        });

        jTabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Kode Barang", "Nama Barang", "Kode Katagori", "Katagori", "Harga Beli", "Harga Jual", "Stok", "Total H Beli", "Total H Jual", "Keterangan"
            }
        ));
        jTabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabelMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTabel);

        btnBaru.setBackground(new java.awt.Color(255, 51, 51));
        btnBaru.setText("New");
        btnBaru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBaruActionPerformed(evt);
            }
        });

        btnSimpan.setBackground(new java.awt.Color(255, 51, 51));
        btnSimpan.setText("Save");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });
        btnSimpan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnSimpanKeyPressed(evt);
            }
        });

        btnEdit.setBackground(new java.awt.Color(255, 51, 51));
        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnHapus.setBackground(new java.awt.Color(255, 51, 51));
        btnHapus.setText("Delete");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnKeluar.setBackground(new java.awt.Color(255, 51, 51));
        btnKeluar.setText("Close");
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtKode, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtNama)
                                    .addComponent(cboKatagori, 0, 180, Short.MAX_VALUE))))
                        .addGap(72, 72, 72)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtHargaB, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(txtHargaJ)
                            .addComponent(txtStok, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBaru, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(88, 88, 88)
                        .addComponent(btnKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 830, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtKode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtHargaB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtHargaJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cboKatagori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtStok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBaru)
                    .addComponent(btnSimpan)
                    .addComponent(btnEdit)
                    .addComponent(btnHapus)
                    .addComponent(btnKeluar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBaruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBaruActionPerformed
        // TODO add your handling code here:
        try 
	{ 
            BersihIsian(); 
            IsiTabel(); 
            txtKode.requestFocus(); 
	} 
	catch (Exception e) 
	{ 
	}
    }//GEN-LAST:event_btnBaruActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        SimpanData();
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        if(txtKode.getText().equals("")) 
	{ 
            JOptionPane.showMessageDialog(null,"Pilih data yang diedit"); 
	}
	else 
	{ 
            try 
            { 
		objStok.AksesData(); 
		objStok.KodeB = txtKode.getText(); 
		objStok.NamaB = txtNama.getText(); 
		objStok.KodeK = cboKatagori.getSelectedItem().toString().substring(0, 3); 
		String mHargaB = txtHargaB.getText(); 
		objStok.HargaBeli = Integer.parseInt(mHargaB);
                String mHargaJ = txtHargaJ.getText(); 
		objStok.HargaJual = Integer.parseInt(mHargaJ);
                String mStok = txtStok.getText(); 
		objStok.Stok = Integer.parseInt(mStok);
		objStok.Edit(); 
		objStok.res.executeUpdate(objStok.sql); 
		objStok.conn.close(); 
		BersihIsian(); 
		IsiTabel(); 
		JOptionPane.showMessageDialog(null,"Data berhasil diupdate"); 
            } 
            catch (Exception e) 
            { 
		JOptionPane.showMessageDialog(null,"Proses penyimpanan gagal/koneksi gagal"); 
		System.out.println(e.getMessage()); 
            } 
	}
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        try 
	{ 
            objStok.AksesData(); 
            objStok.KodeB = txtKode.getText(); 
            objStok.Hapus(objStok.KodeB); 
            objStok.res.executeUpdate(objStok.sql); 
            objStok.conn.close(); 
            IsiTabel(); 
            BersihIsian(); 
            JOptionPane.showMessageDialog(null,"Data berhasil dihapus"); 
	} 
	catch (Exception e) 
	{ 
            JOptionPane.showMessageDialog(null,"Proses penghapusan gagal/koneksi gagal"); 
            System.out.println(e.getMessage()); 
	}
    }//GEN-LAST:event_btnHapusActionPerformed

    private void jTabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabelMouseClicked
        // TODO add your handling code here:
        int baris = jTabel.getSelectedRow(); 
	String kolom1 = jTabel.getValueAt(baris, 0).toString(); 
	String kolom2 = jTabel.getValueAt(baris, 1).toString(); 
	String kolom3 = jTabel.getValueAt(baris, 2).toString() +" : "+ jTabel.getValueAt(baris, 3).toString(); 
	String kolom5 = jTabel.getValueAt(baris, 4).toString();
        String kolom6 = jTabel.getValueAt(baris, 5).toString(); 
        String kolom7 = jTabel.getValueAt(baris, 6).toString(); 
		
	txtKode.setText(kolom1); 
	txtNama.setText(kolom2); 
	cboKatagori.removeAllItems(); 
	cboKatagori.addItem(kolom3);
	txtHargaB.setText(kolom5);
        txtHargaJ.setText(kolom6);
        txtStok.setText(kolom7);
    }//GEN-LAST:event_jTabelMouseClicked

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        // TODO add your handling code here:
        try 
	{ 
            objStok.Keluar(); 
            dispose(); 
	}
	catch (Exception e)
	{ 
            JOptionPane.showMessageDialog(null,"Terjadi kesalahan"); 
            System.out.println(e.getMessage()); 
	}
    }//GEN-LAST:event_btnKeluarActionPerformed

    private void cboKatagoriMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cboKatagoriMouseClicked
        // TODO add your handling code here:
        //Panggil prosedur isi dat adi combobox 
	IsiComboKatagori();
    }//GEN-LAST:event_cboKatagoriMouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        //membuat posisi form ditengah layar 
	Dimension posisi = Toolkit.getDefaultToolkit().getScreenSize(); 
	int x = (posisi.width - this.getWidth())/2; 
	int y = (posisi.height - this.getHeight())/2; 
	this.setLocation(x,y);
    }//GEN-LAST:event_formWindowActivated

    private void txtKodeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtKodeKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode()== KeyEvent.VK_ENTER) 
	{ 
            if ((txtKode.getText().length() < 4) || (txtKode.getText().isEmpty())) 
            { 
		JOptionPane.showMessageDialog(this, "Panjang kode barang harus 4 digit","Informasi", 
		JOptionPane.INFORMATION_MESSAGE); 
		txtKode.requestFocus(); 
            } 
            else 
            { 
		txtNama.requestFocus(); 
            } 
	}
    }//GEN-LAST:event_txtKodeKeyPressed

    private void txtKodeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtKodeKeyTyped
        // TODO add your handling code here:
        //untuk membatasi 4 karakter 
	if (txtKode.getText().length() > 3) 
	evt.consume();
    }//GEN-LAST:event_txtKodeKeyTyped

    private void txtNamaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNamaKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode()== KeyEvent.VK_ENTER) 
	{ 
            if (txtNama.getText().isEmpty()) 
            {
		JOptionPane.showMessageDialog(this, "Nama barang harus diisi","Informasi", 
		JOptionPane.INFORMATION_MESSAGE); 
		txtNama.requestFocus(); 
            } 
            else 
            { 
		cboKatagori.requestFocus(); 
            } 
	}
    }//GEN-LAST:event_txtNamaKeyPressed

    private void txtNamaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNamaKeyTyped
        // TODO add your handling code here:
        if (txtNama.getText().length() > 29) 
	evt.consume();
    }//GEN-LAST:event_txtNamaKeyTyped

    private void cboKatagoriKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cboKatagoriKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode()== KeyEvent.VK_ENTER) 
	{ 
            txtHargaB.requestFocus(); 
	}
    }//GEN-LAST:event_cboKatagoriKeyPressed

    private void txtHargaBKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtHargaBKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode()== KeyEvent.VK_ENTER) 
	{ 
            if (txtKode.getText().isEmpty()) 
            { 
		JOptionPane.showMessageDialog(this, "Silahkan isi harga beli","Informasi", 
		JOptionPane.INFORMATION_MESSAGE); 
		txtHargaB.requestFocus(); 
            } 
            else 
            { 
		btnSimpan.requestFocus(); 
            } 
	}
    }//GEN-LAST:event_txtHargaBKeyPressed

    private void txtHargaBKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtHargaBKeyTyped
        // TODO add your handling code here:
        //Panjang digit harga beli 11 
	if (txtHargaB.getText().length() > 10) 
	evt.consume(); 
		
	//hanya menerima input angka saja 
	char karakter = evt.getKeyChar(); 
	if (!(((karakter>='0') && (karakter <='9')||(karakter == KeyEvent.VK_BACK_SPACE)||(karakter==KeyEvent.VK_DELETE)))) 
	{ 
            getToolkit().beep(); 
            evt.consume(); 
	}
    }//GEN-LAST:event_txtHargaBKeyTyped

    private void txtHargaJKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtHargaJKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode()== KeyEvent.VK_ENTER) 
	{ 
            if (txtKode.getText().isEmpty()) 
            { 
		JOptionPane.showMessageDialog(this, "Silahkan isi harga jual","Informasi", 
		JOptionPane.INFORMATION_MESSAGE); 
		txtHargaJ.requestFocus(); 
            } 
            else 
            { 
		btnSimpan.requestFocus(); 
            } 
	}
    }//GEN-LAST:event_txtHargaJKeyPressed

    private void txtHargaJKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtHargaJKeyTyped
        // TODO add your handling code here:
        //Panjang digit harga jual 11 
	if (txtHargaJ.getText().length() > 10) 
	evt.consume(); 
		
	//hanya menerima input angka saja 
	char karakter = evt.getKeyChar(); 
	if (!(((karakter>='0') && (karakter <='9')||(karakter == KeyEvent.VK_BACK_SPACE)||(karakter==KeyEvent.VK_DELETE)))) 
	{ 
            getToolkit().beep(); 
            evt.consume(); 
	}
    }//GEN-LAST:event_txtHargaJKeyTyped

    private void txtStokKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtStokKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode()== KeyEvent.VK_ENTER) 
	{ 
            if (txtKode.getText().isEmpty()) 
            { 
		JOptionPane.showMessageDialog(this, "Silahkan isi stok barang","Informasi", 
		JOptionPane.INFORMATION_MESSAGE); 
		txtStok.requestFocus(); 
            } 
            else 
            { 
		btnSimpan.requestFocus(); 
            } 
	}
    }//GEN-LAST:event_txtStokKeyPressed

    private void txtStokKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtStokKeyTyped
        // TODO add your handling code here:
        //Panjang digit stok 11 
	if (txtStok.getText().length() > 10) 
	evt.consume(); 
		
	//hanya menerima input angka saja 
	char karakter = evt.getKeyChar(); 
	if (!(((karakter>='0') && (karakter <='9')||(karakter == KeyEvent.VK_BACK_SPACE)||(karakter==KeyEvent.VK_DELETE)))) 
	{ 
            getToolkit().beep(); 
            evt.consume(); 
	}
    }//GEN-LAST:event_txtStokKeyTyped

    private void btnSimpanKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnSimpanKeyPressed
        // TODO add your handling code here:
        SimpanData();
    }//GEN-LAST:event_btnSimpanKeyPressed

    //Prosedur membersihkan isian data 
    public void BersihIsian() 
    { 
	txtKode.setText(""); 
	txtNama.setText(""); 
	IsiComboKatagori(); 
	txtHargaB.setText("");
        txtHargaJ.setText("");
        txtStok.setText("");
	txtKode.requestFocus(); 
    }
    
    //prosedur mengatur kolom jTable 
    private void AturKolom() 
    { 
	jTabel.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
	column = jTabel.getColumnModel().getColumn(0); 
	column.setPreferredWidth(80); 
	column = jTabel.getColumnModel().getColumn(1); 
	column.setPreferredWidth(150); 
	column = jTabel.getColumnModel().getColumn(2); 
	column.setPreferredWidth(80); 
	column = jTabel.getColumnModel().getColumn(3); 
	column.setPreferredWidth(150); 
	column = jTabel.getColumnModel().getColumn(4); 
	column.setPreferredWidth(100);
        column = jTabel.getColumnModel().getColumn(5); 
	column.setPreferredWidth(100); 
        column = jTabel.getColumnModel().getColumn(6); 
	column.setPreferredWidth(80);
        column = jTabel.getColumnModel().getColumn(7); 
	column.setPreferredWidth(100);
        column = jTabel.getColumnModel().getColumn(8); 
	column.setPreferredWidth(100);
        column = jTabel.getColumnModel().getColumn(9); 
	column.setPreferredWidth(150);
    }

    //prosedur simpan data 
    private void SimpanData() 
    { 
	if(txtKode.getText().equals("")||txtNama.getText().equals("")) 
	{ 
            JOptionPane.showMessageDialog(null,"Data harus diisi semua"); 
	} 
	else 
	{ 
            try 
            { 
		objStok.AksesData(); 
		objStok.KodeB = txtKode.getText(); 
		objStok.NamaB = txtNama.getText(); 
		objStok.KodeK = cboKatagori.getSelectedItem().toString().substring(0, 3); 
		String mHargaB = txtHargaB.getText(); 
		objStok.HargaBeli = Integer.parseInt(mHargaB);
                String mHargaJ = txtHargaJ.getText(); 
		objStok.HargaJual = Integer.parseInt(mHargaJ);
                String mStok = txtStok.getText(); 
		objStok.Stok = Integer.parseInt(mStok);
		objStok.Simpan(); 
				
		objStok.res.executeUpdate(objStok.sql); 
		objStok.conn.close(); 
		BersihIsian(); 
		IsiTabel(); 
		JOptionPane.showMessageDialog(null,"Data berhasil disimpan"); 
            } 
            catch (Exception e) 
            { 
		JOptionPane.showMessageDialog(null,"Proses penyimpanan gagal/koneksi gagal"); 
		System.out.println(e.getMessage()); 
            } 
	} 
    }
        
    //Prosedur menampilkan data ke jTable 
    private void IsiTabel() 
    { 
	DefaultTableModel tabelmapel = new DefaultTableModel(); 
		
	tabelmapel.addColumn("Kode Barang"); 
	tabelmapel.addColumn("Nama Barang"); 
	tabelmapel.addColumn("Kode Katagori"); 
	tabelmapel.addColumn("Katagori"); 
	tabelmapel.addColumn("Harga Beli");
        tabelmapel.addColumn("Harga Jual");
        tabelmapel.addColumn("Stok");
        tabelmapel.addColumn("Total H Beli");
        tabelmapel.addColumn("Total H Jual");
        tabelmapel.addColumn("Keterangan");
	try 
	{ 
            objStok.AksesData(); 
            objStok.TampilData(); 
			
            Statement stat1 = objStok.conn.createStatement(); 
            ResultSet res1=stat1.executeQuery(objStok.sql); 
            while (res1.next()) 
            { 
		tabelmapel.addRow(new Object[]{res1.getString(1),res1.getString(2),res1.getString(3),res1.getString(4),res1.getString(5),res1.getString(6),
                    res1.getString(7),res1.getString(8),res1.getString(9),res1.getString(10)}); 
            } 
            jTabel.setModel(tabelmapel); 
            AturKolom(); //atur kolom jTable 
	} 
	catch (Exception e) 
	{ 
	} 
    }
	
    //prosedur mengisi combobox dengan data 
    public void IsiComboKatagori() 
    { 
        try 
	{ 
            cboKatagori.removeAllItems(); 
            objStok.AksesData(); 
            String sql1 = "select * from tblkatagori"; 
            Statement stat1 = objStok.conn.createStatement(); 
            ResultSet res1=stat1.executeQuery(sql1); 
            cboKatagori.addItem("Pilih Katagori"); 
            while(res1.next()) 
            { 
		cboKatagori.addItem(res1.getString("KodeK") + " : " + res1.getString("Katagori")); 
            } 
	} 
	catch(Exception e) 
	{
	} 
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmStok.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmStok.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmStok.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmStok.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmStok().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBaru;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JComboBox<String> cboKatagori;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTabel;
    private javax.swing.JTextField txtHargaB;
    private javax.swing.JTextField txtHargaJ;
    private javax.swing.JTextField txtKode;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtStok;
    // End of variables declaration//GEN-END:variables
}
